name: Build/release macOS

on:
  push:
    #branches: 
    #  - master
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-10.14
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.12
      - name: Install dependencies
        run: npm install
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #- name: Build
      #  run: npm run electron:build
      #  env:
      #    CI: true
      #    GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish
        run: npx vue-cli-service electron:build --publish always
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #- name: Package Artifacts
      #  run: |
      #    mkdir artifact-zip
      #    mv dist_electron/*.zip artifact-zip/
      #- uses: actions/upload-artifact@master
      #  name: Upload ZIP
      #  with:
      #    name: PixieDust-osx.zip
      #    path: artifact-zip