name: CI

on:
  push:
    branches: 
      - master

jobs:
  build_on_mac:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 12.12
      - name: Install dependencies
        run: npm install
      - name: Build Electron
        run: npm run electron:build
      - name: see directory
        run: ls ./dist_electron

  build_on_win:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 12.12
      - name: see directory
        run: ls
